### ISSUE TITLE
[Low Priorirty] Need to integrate the header

### ISSUE THREAD

**Issue by jmardjuki** [TheChyz/Mini-Basketball-League#2]
Just trying to keep note of issue that needs to be addressed eventually. 
Basically all we need is drop down account header (profile, settings, logout)
File we are using:
app/views/layouts/application.html.erb
We do have the header file, just need to work on it
Source
https://www.railstutorial.org/book/log_in_log_out#code-layout_login_logout_links

**Comment by MichaelChyziak** [comment]
I've created the improved header. Since all of our code is in application.html I just moved the relevant code from _header there.
However I removed the "Profile" option from the menu and replaced it with "My Account". In views/welcome/profile Ray made some front-end stuff for the users profile page, so can probably use that as a base for the look of the users profile page.
